# Generated by Django 6.0.3 on 2026-10-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="github_url",
            field=models.URLField(blank=True),
        ),
    ]
